
tasks:
  - name: (Mynechat) Installing dependencies and running app
    init: |
      echo '游붃 游닍 Installing all dependencies'
      yarn
    command: |
      echo '游붃 Running MyneChat application'
      yarn dev
    ## HOPR net repositories
  - name: (HOPRd) Installing hoprnet which contains the required scripts
    command: |
      echo '游리 游닍 Setting up hoprnet repository'
      wget https://github.com/hoprnet/hoprnet/archive/refs/heads/master.zip
      unzip master.zip
      cd hoprnet-master
      echo '游리 游닍 Installing hoprnet repository dependencies'
      yarn
      echo '游리 游닍 Building latest version of hoprnet monorepo'
      yarn build
      echo '游리 Waiting for MyneChat'
      gp await-port 8080
      echo '游리 Running HOPR nodes and topology'
      ./hoprnet-master/scripts/setup-local-cluster.sh -m "$(gp url 8080)" -i hoprnet-master/scripts/topologies/full_interconnected_cluster.sh
    openMode: split-right