
tasks:
  - name: Installing dependencies and running app
    init: |
      yarn
    command: yarn dev
  - name: Installing hoprnet which contains the required scripts
    init: |
      echo '🟡 Downloading hoprnet repository'
      git clone https://github.com/hoprnet/hoprnet.git
      cd hoprnet && yarn && yarn build
    commmand: |
      echo '🟡 Waiting for MyneChat'
      gp await-port 8545
      echo '🟡 Running HOPR nodes & topology'
      ./hoprnet/scripts/setup-local-cluster.sh -m "$(gp url 8080)" -i hoprnet/scripts/topologies/full_interconnected_cluster.sh
    openMode: split-right
ports:
  - port: 8080
    visibility: public