
tasks:
  - name: Installing dependencies and running app
    init: |
      echo '🦄 📦 Installing all dependencies'
      yarn
    command: |
      echo '🦄 Running MyneChat application'
      yarn dev
    ## HOPR net repositories
  - name: Installing hoprnet which contains the required scripts
    init: |
      echo '🟡 📦 Setting up hoprnet repository'
      wget https://github.com/hoprnet/hoprnet/archive/refs/heads/master.zip
      unzip master.zip
